@echo off
echo Configuration du remote Git...
git remote add origin https://github.com/zefparis/romain.git
echo Renommage de la branche en main...
git branch -M main
echo Push vers GitHub...
git push -u origin main
echo Push terminé!
